import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import NavBar from "./components/nav/nav";
import { InterFont } from "./fonts/playfair";
import { Toaster } from "react-hot-toast";
import ReactQueryClientProvider from "./wrappers/react-query";
import ReactCookiesProvider from "./wrappers/react-cookies";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`relative font-sans ${InterFont.variable}`}>
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </Head>

      <body className="absolute top-0">
        <ReactCookiesProvider>
          <NavBar />
          <ReactQueryClientProvider>
            <div className="mt-[0dvh]">{children}</div>
          </ReactQueryClientProvider>
        </ReactCookiesProvider>
      </body>
      <Toaster />
    </html>
  );
}
